#!/usr/bin/env bash
# =============================================================
# deploy.sh - Blue-Green デプロイスクリプト
#
# 現行環境を保全したまま、新バージョンを非アクティブ側に
# デプロイし、ヘルスチェック通過後にトラフィックを切り替える。
#
# Usage:
#   ./scripts/deploy.sh [version-tag]
#
# Examples:
#   ./scripts/deploy.sh              # auto-generate tag from git
#   ./scripts/deploy.sh v1.2.0       # explicit version tag
# =============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_FILE="$PROJECT_DIR/.deploy-state"
NGINX_ACTIVE="$PROJECT_DIR/nginx/active.conf"
IMAGE_NAME="${IMAGE_NAME:-jnavi-app}"
HEALTH_RETRIES=10
HEALTH_INTERVAL=3

# ----- Helpers -----
info()  { echo -e "\033[1;34m[INFO]\033[0m  $*"; }
ok()    { echo -e "\033[1;32m[OK]\033[0m    $*"; }
warn()  { echo -e "\033[1;33m[WARN]\033[0m  $*"; }
error() { echo -e "\033[1;31m[ERROR]\033[0m $*"; exit 1; }

# ----- Determine version tag -----
if [[ -n "${1:-}" ]]; then
    VERSION="$1"
else
    GIT_SHA="$(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
    VERSION="$(date +%Y%m%d-%H%M%S)-${GIT_SHA}"
fi

info "Deploying version: $VERSION"

# ----- Load current state -----
if [[ -f "$STATE_FILE" ]]; then
    source "$STATE_FILE"
else
    ACTIVE_ENV="blue"
    ACTIVE_TAG="initial"
fi

info "Current active environment: $ACTIVE_ENV (tag: ${ACTIVE_TAG:-initial})"

# ----- Determine target (inactive) environment -----
if [[ "$ACTIVE_ENV" == "blue" ]]; then
    TARGET_ENV="green"
else
    TARGET_ENV="blue"
fi

info "Target environment: $TARGET_ENV"

# ----- Build new image -----
info "Building Docker image: $IMAGE_NAME:$VERSION"
docker build -t "$IMAGE_NAME:$VERSION" "$PROJECT_DIR"
docker tag "$IMAGE_NAME:$VERSION" "$IMAGE_NAME:latest"
ok "Image built: $IMAGE_NAME:$VERSION"

# ----- Tag for git reference -----
if git -C "$PROJECT_DIR" rev-parse HEAD &>/dev/null; then
    if ! git -C "$PROJECT_DIR" tag -l "deploy/$VERSION" | grep -q .; then
        git -C "$PROJECT_DIR" tag "deploy/$VERSION"
        ok "Git tag created: deploy/$VERSION"
    fi
fi

# ----- Deploy to target environment -----
info "Deploying to $TARGET_ENV environment..."

# Set environment variables for docker compose
export "${TARGET_ENV^^}_TAG=$VERSION"
export IMAGE_NAME

# Recreate only the target container with the new image
docker compose -f "$PROJECT_DIR/docker-compose.yml" up -d --no-deps --build "app-$TARGET_ENV"
ok "Container app-$TARGET_ENV started with $IMAGE_NAME:$VERSION"

# ----- Health check on target -----
info "Running health check on app-$TARGET_ENV..."
for i in $(seq 1 $HEALTH_RETRIES); do
    if docker exec "jnavi-$TARGET_ENV" wget -qO- http://localhost/health &>/dev/null; then
        ok "Health check passed ($i/$HEALTH_RETRIES)"
        break
    fi
    if [[ $i -eq $HEALTH_RETRIES ]]; then
        error "Health check failed after $HEALTH_RETRIES attempts. Aborting deploy. Current environment ($ACTIVE_ENV) is unchanged."
    fi
    warn "Health check attempt $i/$HEALTH_RETRIES failed, retrying in ${HEALTH_INTERVAL}s..."
    sleep "$HEALTH_INTERVAL"
done

# ----- Switch proxy to target -----
info "Switching proxy to $TARGET_ENV..."

cat > "$NGINX_ACTIVE" <<NGINX_CONF
# Auto-generated by deploy.sh at $(date -Iseconds)
# Active backend: $TARGET_ENV (version: $VERSION)
upstream app_backend {
    server app-$TARGET_ENV:80;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://app_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /health {
        access_log off;
        return 200 'proxy ok';
        add_header Content-Type text/plain;
    }
}
NGINX_CONF

# Reload nginx proxy (zero-downtime)
docker exec jnavi-proxy nginx -s reload
ok "Proxy switched to $TARGET_ENV"

# ----- Save state -----
PREVIOUS_ENV="$ACTIVE_ENV"
PREVIOUS_TAG="${ACTIVE_TAG:-initial}"

cat > "$STATE_FILE" <<STATE
# Deploy state - auto-generated, do not edit manually
ACTIVE_ENV="$TARGET_ENV"
ACTIVE_TAG="$VERSION"
PREVIOUS_ENV="$PREVIOUS_ENV"
PREVIOUS_TAG="$PREVIOUS_TAG"
DEPLOY_TIME="$(date -Iseconds)"
STATE

ok "State saved to $STATE_FILE"

# ----- Summary -----
echo ""
echo "========================================="
echo " Deploy Complete"
echo "========================================="
echo " Version:     $VERSION"
echo " Active:      $TARGET_ENV"
echo " Previous:    $PREVIOUS_ENV (tag: $PREVIOUS_TAG)"
echo " Rollback:    ./scripts/rollback.sh"
echo "========================================="
echo ""
info "The previous environment ($PREVIOUS_ENV) is still running with tag $PREVIOUS_TAG."
info "It will remain available for instant rollback."
