#!/usr/bin/env bash
# =============================================================
# rollback.sh - 前バージョンへの即時ロールバック
#
# proxy の向き先を前回のアクティブ環境に戻すだけなので
# ダウンタイムなしで瞬時にロールバックできる。
#
# Usage:
#   ./scripts/rollback.sh
# =============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_FILE="$PROJECT_DIR/.deploy-state"
NGINX_ACTIVE="$PROJECT_DIR/nginx/active.conf"

# ----- Helpers -----
info()  { echo -e "\033[1;34m[INFO]\033[0m  $*"; }
ok()    { echo -e "\033[1;32m[OK]\033[0m    $*"; }
error() { echo -e "\033[1;31m[ERROR]\033[0m $*"; exit 1; }

# ----- Load state -----
if [[ ! -f "$STATE_FILE" ]]; then
    error "No deploy state found at $STATE_FILE. Nothing to roll back to."
fi

source "$STATE_FILE"

if [[ -z "${PREVIOUS_ENV:-}" || -z "${PREVIOUS_TAG:-}" ]]; then
    error "No previous environment recorded. Cannot roll back."
fi

info "Current active: $ACTIVE_ENV (tag: $ACTIVE_TAG)"
info "Rolling back to: $PREVIOUS_ENV (tag: $PREVIOUS_TAG)"

# ----- Verify previous container is running -----
if ! docker ps --format '{{.Names}}' | grep -q "jnavi-$PREVIOUS_ENV"; then
    error "Container jnavi-$PREVIOUS_ENV is not running. Cannot roll back."
fi

# ----- Health check previous environment -----
info "Verifying health of $PREVIOUS_ENV environment..."
if ! docker exec "jnavi-$PREVIOUS_ENV" wget -qO- http://localhost/health &>/dev/null; then
    error "Health check failed on $PREVIOUS_ENV. Cannot roll back to unhealthy environment."
fi
ok "Health check passed on $PREVIOUS_ENV"

# ----- Switch proxy -----
info "Switching proxy to $PREVIOUS_ENV..."

cat > "$NGINX_ACTIVE" <<NGINX_CONF
# Auto-generated by rollback.sh at $(date -Iseconds)
# Active backend: $PREVIOUS_ENV (version: $PREVIOUS_TAG) [ROLLBACK]
upstream app_backend {
    server app-$PREVIOUS_ENV:80;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://app_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /health {
        access_log off;
        return 200 'proxy ok';
        add_header Content-Type text/plain;
    }
}
NGINX_CONF

docker exec jnavi-proxy nginx -s reload
ok "Proxy switched to $PREVIOUS_ENV"

# ----- Update state (swap active/previous) -----
cat > "$STATE_FILE" <<STATE
# Deploy state - auto-generated, do not edit manually
ACTIVE_ENV="$PREVIOUS_ENV"
ACTIVE_TAG="$PREVIOUS_TAG"
PREVIOUS_ENV="$ACTIVE_ENV"
PREVIOUS_TAG="$ACTIVE_TAG"
DEPLOY_TIME="$(date -Iseconds)"
STATE

ok "State updated"

# ----- Summary -----
echo ""
echo "========================================="
echo " Rollback Complete"
echo "========================================="
echo " Now active:  $PREVIOUS_ENV (tag: $PREVIOUS_TAG)"
echo " Standby:     $ACTIVE_ENV (tag: $ACTIVE_TAG)"
echo "========================================="
echo ""
info "Rollback was instant (proxy switch only). No containers were rebuilt."
info "Run ./scripts/rollback.sh again to switch back if needed."
